Repository googleapis/python-org-policy, pull requests merged in 2021-04, with the labels that each got.

#31 chore: start tracking obsolete files
  synth.metadata
Labels: api: orgpolicy, cla: yes, context: full

#33 chore: Add license headers for python config files
  .pre-commit-config.yaml
  docs/conf.py
  synth.metadata
Labels: api: orgpolicy, automerge, cla: yes, context: full

#34 chore: add constraints file check for python samples
  .github/header-checker-lint.yml
  renovate.json
  synth.metadata
Labels: api: orgpolicy, cla: yes, context: full, samples

#36 chore: prevent normalization of semver versioning
  setup.py
Labels: api: orgpolicy, cla: yes

#39 chore(revert): revert preventing normalization
  setup.py
Labels: api: orgpolicy, cla: yes
